services:
  postgresql:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tareas_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: